"""Append-only event logging for observability."""
from .events import (
    LEADER_FILL_DROP_REASONS,
    WATCHER_MALFORMED_REASONS,
    AmbiguousSubmit,
    FillRecorded,
    KillSwitchTripped,
    LeaderFillDropped,
    LeaderFillObserved,
    MirrorSignalEmitted,
    OrderAcknowledged,
    OrderRejected,
    OrderSubmitted,
    RiskHalt,
    SignalReceived,
    WatcherConnectFailed,
    WatcherMalformedMessage,
    WatcherReconnected,
    WatcherStarted,
    WatcherStopped,
)
from .jsonl_writer import JsonlWriter

__all__ = [
    "AmbiguousSubmit",
    "FillRecorded",
    "JsonlWriter",
    "KillSwitchTripped",
    "LEADER_FILL_DROP_REASONS",
    "LeaderFillDropped",
    "LeaderFillObserved",
    "MirrorSignalEmitted",
    "OrderAcknowledged",
    "OrderRejected",
    "OrderSubmitted",
    "RiskHalt",
    "SignalReceived",
    "WATCHER_MALFORMED_REASONS",
    "WatcherConnectFailed",
    "WatcherMalformedMessage",
    "WatcherReconnected",
    "WatcherStarted",
    "WatcherStopped",
]
