"""Block A1 live OFI and maker diagnostics.

Reads ``data/analysis/block_a1_features.parquet`` generated by
``dali_block_a1_replay_batch.py`` and writes the Block A1 result artifacts.
The analysis is descriptive: no walk-forward split, no ML, and no strategy
deployment verdict.
"""
from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import duckdb
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[1]
ANALYSIS = ROOT / "data" / "analysis"
PLOTS = ANALYSIS / "block_a1_plots"
NOTES = ROOT / "notes"
FEATURES = ANALYSIS / "block_a1_features.parquet"
RESULTS = ANALYSIS / "csv_outputs" / "dali" / "block_a1_results.csv"
DECILES = ANALYSIS / "csv_outputs" / "dali" / "block_a1_decile_aggregate.csv"
SURFACE = ANALYSIS / "csv_outputs" / "dali" / "block_a1_horizon_surface.csv"
NOTE = NOTES / "block_a1_results.md"
TODO = REPO / "brain" / "TODO.md"

HORIZONS = (1, 5, 30, 300)
SURFACE_HORIZONS = (1, 2, 3, 5, 10, 15, 30, 60, 120, 300)
BOOTSTRAP_SAMPLES = 200
BOOTSTRAP_CHUNK_SECONDS = 300
RNG_SEED = 20260528
DEFAULT_WS_LATENCY_MS = 100
MIN_REPORTABLE_CLASSIFIABLE = 30
MIN_REPORTABLE_TOP_DECILE_N = 30
MIN_REPORTABLE_MAKER_FILLS = 30

RESULT_COLUMNS = [
    "run_id",
    "market_id",
    "family",
    "n_book_events",
    "n_trades",
    "n_classifiable",
    "sign_status",
    "mean_effective_spread_bps",
    "mean_depth_at_touch",
    "horizon_sec",
    "strategy_class",
    "ofi_r2",
    "ofi_r2_ci_lo",
    "ofi_r2_ci_hi",
    "ofi_hit_rate_top_decile",
    "ofi_hit_rate_ci_lo",
    "ofi_hit_rate_ci_hi",
    "ofi_top_decile_n",
    "ofi_hit_rate_ci_width",
    "ofi_directional_return_top_decile_bps",
    "ofi_metric_reportable",
    "ofi_hit_rate_top_decile_raw",
    "ofi_directional_return_top_decile_bps_raw",
    "tfi_r2",
    "tfi_hit_rate_top_decile",
    "tfi_top_decile_n",
    "tfi_directional_return_top_decile_bps",
    "tfi_hit_rate_top_decile_raw",
    "maker_fill_count",
    "maker_adverse_selection_bps_5s",
    "maker_net_edge_bps",
    "maker_net_edge_bps_raw",
    "maker_metric_reportable",
    "category_taker_fee_bps",
    "half_spread_cost_bps",
    "ws_latency_slippage_bps",
    "edge_after_cost_bps",
    "edge_after_cost_bps_raw",
    "ws_latency_ms_assumed",
    "sample_size_label",
    "verdict",
]

# Current official Polymarket fee docs as of A1 execution use:
# fee = shares * fee_rate * p * (1 - p). Maker rebate is a percentage
# of the taker fee equivalent and makers are charged zero explicit fee.
FEE_BY_CATEGORY = {
    "Crypto": {"fee_rate": 0.07, "maker_rebate_pct": 0.20},
    "Sports": {"fee_rate": 0.03, "maker_rebate_pct": 0.25},
    "Finance": {"fee_rate": 0.04, "maker_rebate_pct": 0.25},
    "Politics": {"fee_rate": 0.04, "maker_rebate_pct": 0.25},
    "Economics": {"fee_rate": 0.05, "maker_rebate_pct": 0.25},
    "Culture": {"fee_rate": 0.05, "maker_rebate_pct": 0.25},
    "Weather": {"fee_rate": 0.05, "maker_rebate_pct": 0.25},
    "Tech": {"fee_rate": 0.04, "maker_rebate_pct": 0.25},
    "Other": {"fee_rate": 0.05, "maker_rebate_pct": 0.25},
    "Geopolitics": {"fee_rate": 0.0, "maker_rebate_pct": 0.0},
}


@dataclass(frozen=True)
class MetricResult:
    r2: float
    r2_lo: float
    r2_hi: float
    hit_rate: float
    hit_lo: float
    hit_hi: float
    directional_return_bps: float
    n_eval: int
    top_decile_n: int


def display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


def safe_slug(raw: object, fallback: str) -> str:
    text = str(raw or fallback).lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text[:80] or fallback


def family_category(family: object) -> str:
    fam = str(family or "").lower()
    if "crypto" in fam:
        return "Crypto"
    if "sport" in fam or "nba" in fam or "ucl" in fam:
        return "Sports"
    if "geo" in fam or "politic" in fam or "policy" in fam or "iran" in fam:
        return "Geopolitics"
    if "equity" in fam or "stock" in fam or "finance" in fam:
        return "Finance"
    if "ai" in fam or "tech" in fam or "product" in fam:
        return "Tech"
    return "Other"


def taker_fee_bps(
    category: str,
    price: pd.Series | float,
    denominator_price: pd.Series | float | None = None,
) -> pd.Series | float:
    params = FEE_BY_CATEGORY.get(category, FEE_BY_CATEGORY["Other"])
    p = np.clip(price, 0.01, 0.99)
    denom = np.clip(denominator_price if denominator_price is not None else price, 0.01, 0.99)
    return params["fee_rate"] * p * (1.0 - p) / denom * 10_000.0


def maker_rebate_bps(category: str, price: pd.Series | float) -> pd.Series | float:
    params = FEE_BY_CATEGORY.get(category, FEE_BY_CATEGORY["Other"])
    return taker_fee_bps(category, price) * params["maker_rebate_pct"]


def load_features(path: Path) -> pd.DataFrame:
    con = duckdb.connect()
    df = con.execute(f"SELECT * FROM read_parquet('{path}')").df()
    if df.empty:
        raise SystemExit(f"no rows found in {path}")
    df["received_at"] = pd.to_datetime(df["received_at"], utc=True)
    df["exchange_ts"] = pd.to_datetime(df["exchange_ts"], utc=True, errors="coerce")
    for col in ("best_bid", "best_ask", "best_bid_size", "best_ask_size", "spread", "mid"):
        if col in df:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    df["family"] = df["family"].fillna("").astype(str)
    df["market_id"] = df["market_id"].fillna("").astype(str)
    df["asset_id"] = df["asset_id"].fillna("").astype(str)
    df["market_key"] = np.where(df["market_id"].ne(""), df["market_id"], df["asset_id"])
    df["slug"] = df["slug"].fillna("").astype(str)
    df["question"] = df["question"].fillna("").astype(str)
    df["outcome_index"] = pd.to_numeric(df.get("outcome_index"), errors="coerce")
    df["touch_depth"] = df[["best_bid_size", "best_ask_size"]].sum(axis=1, min_count=2)
    df["spread_bps"] = np.where(
        df["mid"].gt(0) & df["spread"].notna(),
        df["spread"] / df["mid"] * 10_000.0,
        np.nan,
    )
    df["is_trade"] = df["event_type"].eq("last_trade_price")
    df["aggressor_side"] = df.get("trade_side", pd.Series(index=df.index, dtype=object)).fillna(
        df.get("last_trade_side", "")
    ).astype(str).str.upper()
    df["trade_price"] = pd.to_numeric(df.get("trade_price"), errors="coerce")
    df["trade_size"] = pd.to_numeric(df.get("trade_size"), errors="coerce")
    side_sign = df["aggressor_side"].map({"BUY": 1.0, "SELL": -1.0}).fillna(0.0)
    df["signed_trade_size_live"] = df["is_trade"].astype(float) * side_sign * df["trade_size"].fillna(0.0)
    df["ofi_combined_event"] = pd.to_numeric(df["ofi_combined_event"], errors="coerce").fillna(0.0)
    df["direction_factor"] = np.where(df["outcome_index"].fillna(0).astype(int).eq(0), 1.0, -1.0)
    df["directional_mid"] = np.where(df["direction_factor"].gt(0), df["mid"], 1.0 - df["mid"])
    df["directional_spread_bps"] = np.where(
        df["directional_mid"].gt(0) & df["spread"].notna(),
        df["spread"] / df["directional_mid"] * 10_000.0,
        np.nan,
    )
    return df.sort_values(["run_id", "asset_id", "received_at"]).reset_index(drop=True)


def add_signal_frames(df: pd.DataFrame, horizons: tuple[int, ...] = HORIZONS) -> pd.DataFrame:
    pieces: list[pd.DataFrame] = []
    for _, group in df.groupby(["run_id", "asset_id"], sort=False):
        g = group.sort_values("received_at").copy()
        g = g.set_index("received_at", drop=False)
        for h in horizons:
            window = f"{h}s"
            g[f"ofi_{h}s"] = g["ofi_combined_event"].rolling(window).sum().to_numpy()
            g[f"tfi_{h}s"] = g["signed_trade_size_live"].rolling(window).sum().to_numpy()
            g[f"future_mid_{h}s"] = future_mid(g, h)
            future_directional_mid = np.where(
                g["direction_factor"].gt(0),
                g[f"future_mid_{h}s"],
                1.0 - g[f"future_mid_{h}s"],
            )
            g[f"ofi_market_{h}s"] = g["direction_factor"] * g[f"ofi_{h}s"]
            g[f"tfi_market_{h}s"] = g["direction_factor"] * g[f"tfi_{h}s"]
            g[f"future_return_bps_{h}s"] = np.where(
                g["directional_mid"].gt(0) & pd.notna(g[f"future_mid_{h}s"]),
                (future_directional_mid - g["directional_mid"]) / g["directional_mid"] * 10_000.0,
                np.nan,
            )
        pieces.append(g.reset_index(drop=True))
    return pd.concat(pieces, ignore_index=True)


def future_mid(g: pd.DataFrame, horizon_sec: int) -> np.ndarray:
    times = g["received_at"].to_numpy(dtype="datetime64[ns]").astype("int64")
    mids = g["mid"].to_numpy(dtype=float)
    target = times + horizon_sec * 1_000_000_000
    last_time = times[-1] if len(times) else 0
    idx = np.searchsorted(times, target, side="right") - 1
    out = np.full(len(g), np.nan, dtype=float)
    valid = (target <= last_time) & (idx >= 0)
    out[valid] = mids[idx[valid]]
    return out


def ols_prediction(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, float]:
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if len(x) < 5 or np.nanstd(x) <= 1e-12 or np.nanstd(y) <= 1e-12:
        return np.array([], dtype=float), math.nan
    x_mean = float(np.mean(x))
    y_mean = float(np.mean(y))
    beta = float(np.sum((x - x_mean) * (y - y_mean)) / np.sum((x - x_mean) ** 2))
    alpha = y_mean - beta * x_mean
    pred = alpha + beta * x
    ss_res = float(np.sum((y - pred) ** 2))
    ss_tot = float(np.sum((y - y_mean) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else math.nan
    return pred, r2


def directional_hit(pred: np.ndarray, y: np.ndarray) -> tuple[float, float, int]:
    mask = np.isfinite(pred) & np.isfinite(y) & (np.sign(pred) != 0) & (np.sign(y) != 0)
    if mask.sum() < 5:
        return math.nan, math.nan, 0
    pred = pred[mask]
    y = y[mask]
    threshold = np.nanquantile(np.abs(pred), 0.90)
    top = np.abs(pred) >= threshold
    if top.sum() < 5:
        return math.nan, math.nan, int(top.sum())
    hits = np.sign(pred[top]) == np.sign(y[top])
    directional_return = np.sign(pred[top]) * y[top]
    return float(hits.mean()), float(np.mean(directional_return)), int(top.sum())


def metric_from_xy(x: np.ndarray, y: np.ndarray) -> tuple[float, float, float, int]:
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    pred, r2 = ols_prediction(x, y)
    if len(pred) == 0:
        return math.nan, math.nan, math.nan, 0
    hit, directional_return, n_top = directional_hit(pred, y)
    return r2, hit, directional_return, n_top


def bootstrap_ci(
    sub: pd.DataFrame,
    x_col: str,
    y_col: str,
    stat: str,
    seed: int,
    samples: int = BOOTSTRAP_SAMPLES,
) -> tuple[float, float]:
    clean = sub[["received_at", x_col, y_col]].dropna()
    if len(clean) < 30:
        return math.nan, math.nan
    elapsed = (clean["received_at"] - clean["received_at"].min()).dt.total_seconds()
    block_id = (elapsed // BOOTSTRAP_CHUNK_SECONDS).astype(int).to_numpy()
    if len(np.unique(block_id)) < 4:
        block_len = max(5, len(clean) // 10)
        block_id = np.arange(len(clean)) // block_len
    blocks = [np.flatnonzero(block_id == bid) for bid in np.unique(block_id)]
    if len(blocks) < 2:
        return math.nan, math.nan
    rng = np.random.default_rng(seed)
    vals: list[float] = []
    x = clean[x_col].to_numpy(dtype=float)
    y = clean[y_col].to_numpy(dtype=float)
    for _ in range(samples):
        sampled = rng.integers(0, len(blocks), size=len(blocks))
        idx = np.concatenate([blocks[i] for i in sampled])
        r2, hit, _, _ = metric_from_xy(x[idx], y[idx])
        value = r2 if stat == "r2" else hit
        if np.isfinite(value):
            vals.append(float(value))
    if len(vals) < 20:
        return math.nan, math.nan
    lo, hi = np.quantile(vals, [0.025, 0.975])
    return float(lo), float(hi)


def compute_metric(sub: pd.DataFrame, x_col: str, y_col: str, seed: int) -> MetricResult:
    clean = sub[["received_at", x_col, y_col]].dropna()
    clean = clean[np.isfinite(clean[x_col]) & np.isfinite(clean[y_col])]
    if len(clean) < 10:
        return MetricResult(
            r2=math.nan,
            r2_lo=math.nan,
            r2_hi=math.nan,
            hit_rate=math.nan,
            hit_lo=math.nan,
            hit_hi=math.nan,
            directional_return_bps=math.nan,
            n_eval=len(clean),
            top_decile_n=0,
        )
    x = clean[x_col].to_numpy(dtype=float)
    y = clean[y_col].to_numpy(dtype=float)
    r2, hit, directional_return, top_decile_n = metric_from_xy(x, y)
    r2_lo, r2_hi = bootstrap_ci(clean, x_col, y_col, "r2", seed)
    hit_lo, hit_hi = bootstrap_ci(clean, x_col, y_col, "hit", seed + 1)
    return MetricResult(
        r2=float(r2) if np.isfinite(r2) else math.nan,
        r2_lo=r2_lo,
        r2_hi=r2_hi,
        hit_rate=float(hit) if np.isfinite(hit) else math.nan,
        hit_lo=hit_lo,
        hit_hi=hit_hi,
        directional_return_bps=float(directional_return) if np.isfinite(directional_return) else math.nan,
        n_eval=len(clean),
        top_decile_n=int(top_decile_n),
    )


def sample_size_label(n_classifiable: int) -> str:
    if n_classifiable < 30:
        return "insufficient"
    if n_classifiable < 200:
        return "thin_wide_CI"
    return "primary_read"


def verdict(n_classifiable: int, hit: float, directional_return: float, edge_after_cost: float) -> str:
    if n_classifiable < 30:
        return "data_thin"
    if np.isfinite(edge_after_cost) and edge_after_cost > 0:
        return "signal_present_post_cost"
    if (
        np.isfinite(hit)
        and np.isfinite(directional_return)
        and hit >= 0.53
        and directional_return > 0
    ):
        return "signal_present_pre_cost"
    return "absent"


def metric_reportable(n_classifiable: int, metric: MetricResult) -> bool:
    return (
        n_classifiable >= MIN_REPORTABLE_CLASSIFIABLE
        and metric.n_eval >= MIN_REPORTABLE_CLASSIFIABLE
        and metric.top_decile_n >= MIN_REPORTABLE_TOP_DECILE_N
        and np.isfinite(metric.hit_rate)
        and 0.0 < metric.hit_rate < 1.0
    )


def maker_reportable(n_classifiable: int, maker_fill_count: int) -> bool:
    return (
        n_classifiable >= MIN_REPORTABLE_CLASSIFIABLE
        and maker_fill_count >= MIN_REPORTABLE_MAKER_FILLS
    )


def public_value(value: float, reportable: bool) -> float:
    return float(value) if reportable and np.isfinite(value) else math.nan


def ci_width(lo: float, hi: float) -> float:
    return float(hi - lo) if np.isfinite(lo) and np.isfinite(hi) else math.nan


def latency_slippage_bps(
    sub: pd.DataFrame,
    latency_ms: int,
    price_col: str = "directional_mid",
) -> float:
    if sub.empty:
        return math.nan
    h = max(latency_ms / 1000.0, 0.001)
    g = sub.sort_values("received_at").copy()
    times = g["received_at"].to_numpy(dtype="datetime64[ns]").astype("int64")
    price_series = g[price_col] if price_col in g else g["mid"]
    prices = price_series.to_numpy(dtype=float)
    target = times + int(h * 1_000_000_000)
    idx = np.searchsorted(times, target, side="right") - 1
    valid = (
        (target <= times[-1])
        & (idx >= 0)
        & np.isfinite(prices)
        & np.isfinite(prices[idx])
        & (prices > 0)
    )
    if valid.sum() < 5:
        return 0.0
    move = np.abs((prices[idx[valid]] - prices[valid]) / prices[valid] * 10_000.0)
    return float(np.nanmean(move))


def maker_fills(sub: pd.DataFrame, horizon_sec: int) -> pd.DataFrame:
    trades = sub[sub["is_trade"]].copy()
    if trades.empty:
        return pd.DataFrame()
    trades = trades[
        trades["mid"].notna()
        & trades["trade_price"].notna()
        & trades["trade_size"].fillna(0).gt(0)
        & trades["aggressor_side"].isin(["BUY", "SELL"])
    ].copy()
    if trades.empty:
        return trades
    price = trades["trade_price"].astype(float)
    bid = trades["best_bid"].astype(float)
    ask = trades["best_ask"].astype(float)
    buy_fill = trades["aggressor_side"].eq("SELL") & price.le(bid + 1e-9)
    sell_fill = trades["aggressor_side"].eq("BUY") & price.ge(ask - 1e-9)
    fills = trades[buy_fill | sell_fill].copy()
    if fills.empty:
        return fills
    fills["maker_side"] = np.where(fills["aggressor_side"].eq("SELL"), "BUY", "SELL")
    fut = fills[f"future_mid_{horizon_sec}s"].astype(float)
    fill_px = fills["trade_price"].astype(float)
    fills[f"adverse_selection_bps_{horizon_sec}s"] = np.where(
        fills["maker_side"].eq("BUY"),
        (fill_px - fut) / fill_px * 10_000.0,
        (fut - fill_px) / fill_px * 10_000.0,
    )
    fills["fill_volume_usd"] = fill_px * fills["trade_size"].astype(float)
    fills["category"] = fills["family"].map(family_category)
    fills["rebate_bps"] = [
        maker_rebate_bps(cat, px) for cat, px in zip(fills["category"], fill_px, strict=False)
    ]
    return fills


def market_panel(df: pd.DataFrame, ws_latency_ms: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    rows: list[dict[str, object]] = []
    maker_rows: list[pd.DataFrame] = []
    group_cols = ["run_id", "market_key"]
    for group_idx, ((run_id, market_key), sub) in enumerate(df.groupby(group_cols, sort=False)):
        sub = sub.sort_values("received_at")
        market_id = str(sub["market_id"].dropna().replace("", np.nan).dropna().iloc[0]) if sub["market_id"].astype(bool).any() else str(market_key)
        family = str(sub["family"].dropna().replace("", np.nan).dropna().iloc[0]) if sub["family"].astype(bool).any() else ""
        slug = str(sub["slug"].dropna().replace("", np.nan).dropna().iloc[0]) if sub["slug"].astype(bool).any() else ""
        question = str(sub["question"].dropna().replace("", np.nan).dropna().iloc[0]) if sub["question"].astype(bool).any() else ""
        category = family_category(family)
        n_book_events = int(sub["event_type"].isin(["book", "price_change"]).sum())
        trades = sub[sub["is_trade"]]
        n_trades = int(len(trades))
        n_classifiable = int(trades["aggressor_side"].isin(["BUY", "SELL"]).sum())
        mean_spread = float(sub["spread_bps"].replace([np.inf, -np.inf], np.nan).mean())
        median_spread = float(sub["spread_bps"].replace([np.inf, -np.inf], np.nan).median())
        p10_spread = float(sub["spread_bps"].replace([np.inf, -np.inf], np.nan).quantile(0.10))
        p90_spread = float(sub["spread_bps"].replace([np.inf, -np.inf], np.nan).quantile(0.90))
        mean_cost_spread = float(sub["directional_spread_bps"].replace([np.inf, -np.inf], np.nan).mean())
        half_spread_cost = 0.5 * mean_cost_spread if np.isfinite(mean_cost_spread) else math.nan
        mean_depth = float(sub["touch_depth"].replace([np.inf, -np.inf], np.nan).mean())
        latency_bps = latency_slippage_bps(sub, ws_latency_ms, "directional_mid")
        fee_input = sub[["mid", "directional_mid"]].dropna()
        fee_bps = (
            float(taker_fee_bps(category, fee_input["mid"], fee_input["directional_mid"]).mean())
            if not fee_input.empty
            else math.nan
        )

        maker_5s = maker_fills(sub, 5)
        maker_fill_count = int(len(maker_5s))
        maker_volume = float(maker_5s["fill_volume_usd"].sum()) if not maker_5s.empty else 0.0
        maker_rebate = float(maker_5s["rebate_bps"].mean()) if not maker_5s.empty else math.nan
        maker_adv_1 = float(maker_fills(sub, 1).get("adverse_selection_bps_1s", pd.Series(dtype=float)).mean())
        maker_adv_5 = float(maker_5s.get("adverse_selection_bps_5s", pd.Series(dtype=float)).mean())
        maker_adv_30 = float(maker_fills(sub, 30).get("adverse_selection_bps_30s", pd.Series(dtype=float)).mean())
        maker_net = maker_rebate - maker_adv_5 if np.isfinite(maker_rebate) and np.isfinite(maker_adv_5) else math.nan
        if not maker_5s.empty:
            maker_rows.append(maker_5s.assign(panel_slug=slug, panel_question=question))

        for horizon in HORIZONS:
            y_col = f"future_return_bps_{horizon}s"
            ofi_col = f"ofi_market_{horizon}s"
            tfi_col = f"tfi_market_{horizon}s"
            valid = sub[
                sub["is_book_state_complete"].fillna(False)
                & sub["mid"].notna()
                & sub[y_col].notna()
            ].copy()
            ofi_eval = valid[valid[ofi_col].abs() > 1e-12]
            tfi_eval = valid[valid[tfi_col].abs() > 1e-12]
            ofi = compute_metric(ofi_eval, ofi_col, y_col, RNG_SEED + group_idx * 100 + horizon)
            tfi = compute_metric(tfi_eval, tfi_col, y_col, RNG_SEED + group_idx * 100 + horizon + 10)
            ofi_is_reportable = metric_reportable(n_classifiable, ofi)
            tfi_is_reportable = metric_reportable(n_classifiable, tfi)
            maker_is_reportable = maker_reportable(n_classifiable, maker_fill_count)
            raw_edge = (
                ofi.directional_return_bps
                - fee_bps
                - half_spread_cost
                - latency_bps
                if all(np.isfinite(v) for v in [ofi.directional_return_bps, fee_bps, half_spread_cost, latency_bps])
                else math.nan
            )
            edge = public_value(raw_edge, ofi_is_reportable)
            ofi_hit = public_value(ofi.hit_rate, ofi_is_reportable)
            ofi_directional_return = public_value(ofi.directional_return_bps, ofi_is_reportable)
            tfi_hit = public_value(tfi.hit_rate, tfi_is_reportable)
            tfi_directional_return = public_value(tfi.directional_return_bps, tfi_is_reportable)
            maker_net_public = public_value(maker_net, maker_is_reportable)
            label = sample_size_label(n_classifiable)
            rows.append({
                "run_id": run_id,
                "market_id": market_id,
                "asset_id": ",".join(sorted(sub["asset_id"].dropna().astype(str).unique())[:4]),
                "slug": slug,
                "question": question,
                "family": family,
                "category": category,
                "n_book_events": n_book_events,
                "n_trades": n_trades,
                "n_classifiable": n_classifiable,
                "sign_status": "live_reported_side_is_aggressor",
                "mean_effective_spread_bps": mean_spread,
                "median_effective_spread_bps": median_spread,
                "p10_effective_spread_bps": p10_spread,
                "p90_effective_spread_bps": p90_spread,
                "mean_depth_at_touch": mean_depth,
                "horizon_sec": horizon,
                "strategy_class": "signal_and_maker_proxy",
                "ofi_r2": public_value(ofi.r2, ofi_is_reportable),
                "ofi_r2_ci_lo": public_value(ofi.r2_lo, ofi_is_reportable),
                "ofi_r2_ci_hi": public_value(ofi.r2_hi, ofi_is_reportable),
                "ofi_hit_rate_top_decile": ofi_hit,
                "ofi_hit_rate_ci_lo": public_value(ofi.hit_lo, ofi_is_reportable),
                "ofi_hit_rate_ci_hi": public_value(ofi.hit_hi, ofi_is_reportable),
                "ofi_top_decile_n": ofi.top_decile_n,
                "ofi_hit_rate_ci_width": public_value(ci_width(ofi.hit_lo, ofi.hit_hi), ofi_is_reportable),
                "ofi_directional_return_top_decile_bps": ofi_directional_return,
                "ofi_metric_reportable": ofi_is_reportable,
                "ofi_hit_rate_top_decile_raw": ofi.hit_rate,
                "ofi_directional_return_top_decile_bps_raw": ofi.directional_return_bps,
                "ofi_eval_rows": ofi.n_eval,
                "tfi_r2": public_value(tfi.r2, tfi_is_reportable),
                "tfi_hit_rate_top_decile": tfi_hit,
                "tfi_top_decile_n": tfi.top_decile_n,
                "tfi_directional_return_top_decile_bps": tfi_directional_return,
                "tfi_hit_rate_top_decile_raw": tfi.hit_rate,
                "tfi_directional_return_top_decile_bps_raw": tfi.directional_return_bps,
                "tfi_eval_rows": tfi.n_eval,
                "maker_fill_count": maker_fill_count,
                "maker_fill_volume_usd": maker_volume,
                "maker_adverse_selection_bps_1s": maker_adv_1,
                "maker_adverse_selection_bps_5s": maker_adv_5,
                "maker_adverse_selection_bps_30s": maker_adv_30,
                "gross_rebate_bps": maker_rebate,
                "maker_net_edge_bps": maker_net_public,
                "maker_net_edge_bps_raw": maker_net,
                "maker_metric_reportable": maker_is_reportable,
                "edge_after_cost_bps": edge,
                "edge_after_cost_bps_raw": raw_edge,
                "category_taker_fee_bps": fee_bps,
                "half_spread_cost_bps": half_spread_cost,
                "ws_latency_ms_assumed": ws_latency_ms,
                "ws_latency_slippage_bps": latency_bps,
                "sample_size_label": label,
                "verdict": verdict(n_classifiable, ofi_hit, ofi_directional_return, edge),
            })
    maker_df = pd.concat(maker_rows, ignore_index=True) if maker_rows else pd.DataFrame()
    return pd.DataFrame(rows), maker_df


def decile_aggregate(df: pd.DataFrame, results: pd.DataFrame) -> pd.DataFrame:
    depth = (
        results.groupby(["run_id", "market_id"], as_index=False)["mean_depth_at_touch"]
        .first()
        .rename(columns={"mean_depth_at_touch": "market_mean_depth"})
    )
    out_rows: list[dict[str, object]] = []
    base = df.merge(
        depth,
        left_on=["run_id", "market_key"],
        right_on=["run_id", "market_id"],
        how="left",
        suffixes=("", "_depth"),
    )
    for horizon in HORIZONS:
        sig = f"ofi_market_{horizon}s"
        y = f"future_return_bps_{horizon}s"
        sub = base[
            base["is_book_state_complete"].fillna(False)
            & base[sig].notna()
            & base[y].notna()
            & base["market_mean_depth"].gt(0)
        ].copy()
        sub["ofi_scaled"] = sub[sig] / sub["market_mean_depth"]
        sub = sub[np.isfinite(sub["ofi_scaled"]) & sub["ofi_scaled"].ne(0) & np.isfinite(sub[y])]
        if len(sub) < 50:
            continue
        sub["abs_signal"] = sub["ofi_scaled"].abs()
        try:
            sub["decile"] = pd.qcut(sub["abs_signal"], 10, labels=False, duplicates="drop") + 1
        except ValueError:
            continue
        for decile, rows in sub.groupby("decile", sort=True):
            rows = rows.copy()
            hit = np.sign(rows["ofi_scaled"]) == np.sign(rows[y])
            hit = hit[(np.sign(rows["ofi_scaled"]) != 0) & (np.sign(rows[y]) != 0)]
            hit_rate = float(hit.mean()) if len(hit) else math.nan
            lo, hi = block_bootstrap_hit(rows, "ofi_scaled", y, RNG_SEED + horizon * 100 + int(decile))
            out_rows.append({
                "horizon_sec": horizon,
                "decile": int(decile),
                "n": int(len(rows)),
                "mean_abs_ofi_scaled": float(rows["abs_signal"].mean()),
                "mean_next_mid_return_bps": float(rows[y].mean()),
                "directional_return_bps": float((np.sign(rows["ofi_scaled"]) * rows[y]).mean()),
                "hit_rate": hit_rate,
                "hit_rate_ci_lo": lo,
                "hit_rate_ci_hi": hi,
            })
    return pd.DataFrame(out_rows)


def ofi_level(decile: int) -> str:
    if decile <= 3:
        return "low"
    if decile <= 7:
        return "middle"
    if decile <= 9:
        return "high"
    return "extreme"


def horizon_surface_aggregate(df: pd.DataFrame, results: pd.DataFrame) -> pd.DataFrame:
    depth = (
        results.groupby(["run_id", "market_id"], as_index=False)["mean_depth_at_touch"]
        .first()
        .rename(columns={"mean_depth_at_touch": "market_mean_depth"})
    )
    base = df.merge(
        depth,
        left_on=["run_id", "market_key"],
        right_on=["run_id", "market_id"],
        how="left",
        suffixes=("", "_depth"),
    )
    out_rows: list[dict[str, object]] = []
    for horizon in SURFACE_HORIZONS:
        sig = f"ofi_market_{horizon}s"
        y = f"future_return_bps_{horizon}s"
        sub = base[
            base["is_book_state_complete"].fillna(False)
            & base[sig].notna()
            & base[y].notna()
            & base["market_mean_depth"].gt(0)
        ].copy()
        sub["ofi_scaled"] = sub[sig] / sub["market_mean_depth"]
        sub = sub[np.isfinite(sub["ofi_scaled"]) & sub["ofi_scaled"].ne(0) & np.isfinite(sub[y])]
        if len(sub) < 50:
            continue
        sub["abs_signal"] = sub["ofi_scaled"].abs()
        try:
            sub["decile"] = pd.qcut(sub["abs_signal"], 10, labels=False, duplicates="drop") + 1
        except ValueError:
            continue
        for decile, rows in sub.groupby("decile", sort=True):
            rows = rows.copy()
            signs = (np.sign(rows["ofi_scaled"]) != 0) & (np.sign(rows[y]) != 0)
            hit_rate = (
                float((np.sign(rows.loc[signs, "ofi_scaled"]) == np.sign(rows.loc[signs, y])).mean())
                if signs.any()
                else math.nan
            )
            fam_share = rows["family"].value_counts(normalize=True, dropna=False)
            top_family = str(fam_share.index[0]) if len(fam_share) else ""
            top_family_share = float(fam_share.iloc[0]) if len(fam_share) else math.nan
            out_rows.append({
                "horizon_sec": horizon,
                "decile": int(decile),
                "ofi_level": ofi_level(int(decile)),
                "n": int(len(rows)),
                "mean_abs_ofi_scaled": float(rows["abs_signal"].mean()),
                "mean_next_mid_return_bps": float(rows[y].mean()),
                "directional_return_bps": float((np.sign(rows["ofi_scaled"]) * rows[y]).mean()),
                "hit_rate": hit_rate,
                "mean_spread_bps": float(rows["spread_bps"].replace([np.inf, -np.inf], np.nan).mean()),
                "mean_touch_depth": float(rows["touch_depth"].replace([np.inf, -np.inf], np.nan).mean()),
                "top_family": top_family,
                "top_family_share": top_family_share,
            })
    return pd.DataFrame(out_rows)


def block_bootstrap_hit(sub: pd.DataFrame, x_col: str, y_col: str, seed: int) -> tuple[float, float]:
    clean = sub[["received_at", x_col, y_col]].dropna()
    if len(clean) < 30:
        return math.nan, math.nan
    elapsed = (clean["received_at"] - clean["received_at"].min()).dt.total_seconds()
    block_id = (elapsed // BOOTSTRAP_CHUNK_SECONDS).astype(int).to_numpy()
    if len(np.unique(block_id)) < 4:
        block_id = np.arange(len(clean)) // max(5, len(clean) // 10)
    blocks = [np.flatnonzero(block_id == bid) for bid in np.unique(block_id)]
    rng = np.random.default_rng(seed)
    x = clean[x_col].to_numpy(dtype=float)
    y = clean[y_col].to_numpy(dtype=float)
    vals: list[float] = []
    for _ in range(BOOTSTRAP_SAMPLES):
        idx = np.concatenate([blocks[i] for i in rng.integers(0, len(blocks), size=len(blocks))])
        mask = (np.sign(x[idx]) != 0) & (np.sign(y[idx]) != 0)
        if mask.sum() >= 5:
            vals.append(float((np.sign(x[idx][mask]) == np.sign(y[idx][mask])).mean()))
    if len(vals) < 20:
        return math.nan, math.nan
    lo, hi = np.quantile(vals, [0.025, 0.975])
    return float(lo), float(hi)


def plot_deciles(deciles: pd.DataFrame) -> list[Path]:
    paths: list[Path] = []
    PLOTS.mkdir(parents=True, exist_ok=True)
    for horizon, sub in deciles.groupby("horizon_sec"):
        fig, ax = plt.subplots(figsize=(7.5, 4.5))
        ax.plot(sub["decile"], sub["hit_rate"], marker="o", color="#1f77b4")
        ax.fill_between(
            sub["decile"].astype(float),
            sub["hit_rate_ci_lo"].astype(float),
            sub["hit_rate_ci_hi"].astype(float),
            color="#1f77b4",
            alpha=0.15,
        )
        ax.axhline(0.50, color="#666666", linewidth=1, linestyle="--")
        ax.set_title(f"Depth-normalized OFI hit rate, {horizon}s")
        ax.set_xlabel("Absolute OFI_scaled decile")
        ax.set_ylabel("Hit rate")
        ax.set_ylim(0.0, 1.0)
        ax.grid(True, alpha=0.25)
        out = PLOTS / f"block_a1_decile_hit_rate_{int(horizon)}s.png"
        fig.tight_layout()
        fig.savefig(out, dpi=160)
        plt.close(fig)
        paths.append(out)
    return paths


def surface_matrix(surface: pd.DataFrame, value_col: str) -> tuple[np.ndarray, list[int], list[int]]:
    horizons = sorted(surface["horizon_sec"].dropna().astype(int).unique())
    deciles = sorted(surface["decile"].dropna().astype(int).unique())
    mat = (
        surface.pivot(index="decile", columns="horizon_sec", values=value_col)
        .reindex(index=deciles, columns=horizons)
        .to_numpy(dtype=float)
    )
    return mat, horizons, deciles


def plot_surface_heatmap(
    surface: pd.DataFrame,
    value_col: str,
    title: str,
    filename: str,
    cmap: str,
    center: float | None = None,
) -> Path | None:
    if surface.empty:
        return None
    mat, horizons, deciles = surface_matrix(surface, value_col)
    if mat.size == 0 or np.all(~np.isfinite(mat)):
        return None
    PLOTS.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(9, 5.5))
    if center is not None:
        vmax = float(np.nanmax(np.abs(mat - center)))
        vmin = center - vmax
        vmax = center + vmax
    else:
        vmin = float(np.nanmin(mat))
        vmax = float(np.nanmax(mat))
    im = ax.imshow(mat, origin="lower", aspect="auto", cmap=cmap, vmin=vmin, vmax=vmax)
    ax.set_title(title)
    ax.set_xlabel("Forward horizon")
    ax.set_ylabel("Absolute OFI_scaled decile")
    ax.set_xticks(np.arange(len(horizons)))
    ax.set_xticklabels([f"{h}s" for h in horizons], rotation=35, ha="right")
    ax.set_yticks(np.arange(len(deciles)))
    ax.set_yticklabels([str(d) for d in deciles])
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label(value_col)
    fig.tight_layout()
    out = PLOTS / filename
    fig.savefig(out, dpi=160)
    plt.close(fig)
    return out


def plot_surface_3d(surface: pd.DataFrame) -> Path | None:
    if surface.empty:
        return None
    mat, horizons, deciles = surface_matrix(surface, "hit_rate")
    if mat.size == 0 or np.all(~np.isfinite(mat)):
        return None
    PLOTS.mkdir(parents=True, exist_ok=True)
    x = np.log10(np.array(horizons, dtype=float))
    y = np.array(deciles, dtype=float)
    xx, yy = np.meshgrid(x, y)
    fig = plt.figure(figsize=(9, 6.5))
    ax = fig.add_subplot(111, projection="3d")
    norm = plt.Normalize(vmin=0.35, vmax=0.75)
    surf = ax.plot_surface(
        xx,
        yy,
        mat,
        cmap="viridis",
        norm=norm,
        linewidth=0,
        antialiased=True,
        alpha=0.94,
    )
    ax.set_title("Depth-normalized OFI hit-rate surface")
    ax.set_xlabel("Forward horizon")
    ax.set_ylabel("Absolute OFI_scaled decile")
    ax.set_zlabel("Hit rate")
    ax.set_xticks(x)
    ax.set_xticklabels([f"{h}s" for h in horizons], rotation=20, ha="right")
    ax.set_yticks(deciles)
    ax.set_zlim(0.35, 0.80)
    fig.colorbar(surf, ax=ax, shrink=0.62, pad=0.12, label="hit_rate")
    fig.subplots_adjust(left=0.02, right=0.86, bottom=0.05, top=0.92)
    out = PLOTS / "block_a1_ofi_surface_hit_rate_3d.png"
    fig.savefig(out, dpi=170)
    plt.close(fig)
    return out


def plot_surface_diagnostics(surface: pd.DataFrame) -> list[Path]:
    paths: list[Path] = []
    p3d = plot_surface_3d(surface)
    if p3d:
        paths.append(p3d)
    for path in (
        plot_surface_heatmap(
            surface,
            "hit_rate",
            "Depth-normalized OFI hit rate by horizon and magnitude",
            "block_a1_ofi_surface_hit_rate_heatmap.png",
            "viridis",
            center=None,
        ),
        plot_surface_heatmap(
            surface,
            "directional_return_bps",
            "Directional return by horizon and OFI magnitude",
            "block_a1_ofi_surface_directional_return_heatmap.png",
            "coolwarm",
            center=0.0,
        ),
        plot_surface_heatmap(
            surface,
            "top_family_share",
            "Dominant-family share by horizon and OFI magnitude",
            "block_a1_ofi_surface_family_share_heatmap.png",
            "magma",
            center=None,
        ),
    ):
        if path:
            paths.append(path)
    return paths


def plot_scatters(df: pd.DataFrame, results: pd.DataFrame) -> list[Path]:
    paths: list[Path] = []
    PLOTS.mkdir(parents=True, exist_ok=True)
    top_assets = (
        results[results["horizon_sec"].eq(30)]
        .sort_values(["n_classifiable", "ofi_eval_rows"], ascending=False)
        [["run_id", "market_id", "slug"]]
        .drop_duplicates()
        .head(12)
    )
    for _, row in top_assets.iterrows():
        sub = df[df["run_id"].eq(row["run_id"]) & df["market_key"].eq(row["market_id"])].copy()
        sub = sub[np.isfinite(sub["ofi_market_30s"]) & np.isfinite(sub["future_return_bps_30s"])]
        if len(sub) < 20:
            continue
        if len(sub) > 5_000:
            sub = sub.sample(5_000, random_state=RNG_SEED)
        fig, ax = plt.subplots(figsize=(6.5, 4.5))
        ax.scatter(sub["ofi_market_30s"], sub["future_return_bps_30s"], s=6, alpha=0.25, color="#2b6cb0")
        ax.axhline(0, color="#666666", linewidth=1)
        ax.axvline(0, color="#666666", linewidth=1)
        ax.set_title(f"OFI vs 30s return: {row['slug'] or row['asset_id'][:8]}")
        ax.set_xlabel("30s OFI")
        ax.set_ylabel("Forward 30s mid-return (bps)")
        ax.grid(True, alpha=0.2)
        out = PLOTS / f"block_a1_ofi_scatter_{row['run_id']}_{safe_slug(row['slug'], str(row['market_id'])[:10])}.png"
        fig.tight_layout()
        fig.savefig(out, dpi=160)
        plt.close(fig)
        paths.append(out)
    return paths


def plot_maker_timeline(maker: pd.DataFrame) -> Path | None:
    if maker.empty:
        return None
    PLOTS.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(9, 4.8))
    plot_df = maker.copy()
    if len(plot_df) > 10_000:
        plot_df = plot_df.sample(10_000, random_state=RNG_SEED)
    y = plot_df["adverse_selection_bps_5s"].clip(-500, 500)
    ax.scatter(plot_df["received_at"], y, s=8, alpha=0.35, color="#805ad5")
    ax.axhline(0, color="#666666", linewidth=1)
    ax.set_title("Passive maker fills, 5s adverse selection")
    ax.set_xlabel("Capture time")
    ax.set_ylabel("Adverse selection bps (clipped)")
    ax.grid(True, alpha=0.2)
    out = PLOTS / "block_a1_maker_fill_timeline.png"
    fig.tight_layout()
    fig.savefig(out, dpi=160)
    plt.close(fig)
    return out


def pct(x: float) -> str:
    if not np.isfinite(x):
        return "n/a"
    return f"{100.0 * x:.1f}%"


def bps(x: float) -> str:
    if not np.isfinite(x):
        return "n/a"
    return f"{x:.1f} bps"


def rel_plot(path: Path) -> str:
    return str(path.resolve().relative_to(NOTES.resolve().parent))


def family_rollup(results: pd.DataFrame) -> pd.DataFrame:
    h5 = results[results["horizon_sec"].eq(5)].copy()
    if h5.empty:
        return pd.DataFrame()
    h5["reportable_markets"] = h5["ofi_metric_reportable"].fillna(False).astype(bool)
    return (
        h5.groupby("category", as_index=False)
        .agg(
            n_markets=("market_id", "nunique"),
            n_trades=("n_trades", "sum"),
            primary_markets=("sample_size_label", lambda s: int((s == "primary_read").sum())),
            reportable_markets=("reportable_markets", "sum"),
            median_5s_hit=("ofi_hit_rate_top_decile", "median"),
            mean_edge_after_cost_bps=("edge_after_cost_bps", "mean"),
            mean_maker_net_bps=("maker_net_edge_bps", "mean"),
        )
        .sort_values("n_trades", ascending=False)
    )


def decile_row(deciles: pd.DataFrame, horizon_sec: int, decile: int) -> pd.Series | None:
    sub = deciles[deciles["horizon_sec"].eq(horizon_sec)]
    if sub.empty:
        return None
    row = sub[sub["decile"].eq(decile)]
    if row.empty:
        return None
    return row.iloc[0]


def decile_sentence(row: pd.Series | None) -> str:
    if row is None:
        return "not available"
    return (
        f"{int(row['horizon_sec'])}s/decile {int(row['decile'])}: "
        f"{pct(float(row['hit_rate']))} hit "
        f"(CI [{pct(float(row['hit_rate_ci_lo']))}, {pct(float(row['hit_rate_ci_hi']))}], "
        f"n={int(row['n']):,}), directional return {bps(float(row['directional_return_bps']))}"
    )


def fmt_cell(value: object, kind: str = "text") -> str:
    if pd.isna(value):
        return "n/a"
    if kind == "pct":
        return pct(float(value))
    if kind == "bps":
        return bps(float(value))
    if kind == "int":
        return f"{int(value):,}"
    if kind == "float":
        return f"{float(value):.2f}"
    text = str(value)
    return text.replace("|", "/")


def markdown_table(headers: list[str], rows: list[list[object]]) -> str:
    if not rows:
        return "_No rows._"
    header = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = ["| " + " | ".join(str(cell) for cell in row) + " |" for row in rows]
    return "\n".join([header, sep, *body])


def short_market(row: pd.Series) -> str:
    slug = str(row.get("slug") or "")
    if slug:
        return slug[:58]
    return str(row.get("market_id", ""))


def per_market_table(results: pd.DataFrame, horizon_sec: int = 5) -> str:
    sub = results[results["horizon_sec"].eq(horizon_sec)].copy()
    if sub.empty:
        return "_No market rows._"
    sub = sub.sort_values(
        ["ofi_metric_reportable", "n_classifiable", "ofi_hit_rate_top_decile_raw"],
        ascending=[False, False, False],
    )
    rows: list[list[object]] = []
    for _, row in sub.iterrows():
        rows.append([
            fmt_cell(row["run_id"]),
            short_market(row),
            fmt_cell(row["family"]),
            fmt_cell(row["n_classifiable"], "int"),
            fmt_cell(row["sample_size_label"]),
            fmt_cell(row["ofi_hit_rate_top_decile"], "pct"),
            fmt_cell(row["ofi_top_decile_n"], "int"),
            fmt_cell(row["ofi_directional_return_top_decile_bps"], "bps"),
            fmt_cell(row["edge_after_cost_bps"], "bps"),
            fmt_cell(row["verdict"]),
        ])
    return markdown_table(
        ["run", "market", "family", "n class", "label", "5s hit", "top n", "5s dir ret", "cost edge", "verdict"],
        rows,
    )


def high_hit_table(results: pd.DataFrame) -> str:
    sub = results[
        results["ofi_hit_rate_top_decile_raw"].ge(0.80)
        | results["ofi_hit_rate_top_decile"].ge(0.70)
    ].copy()
    if sub.empty:
        return "_No high-hit rows._"
    sub = sub.sort_values(
        ["ofi_metric_reportable", "horizon_sec", "ofi_hit_rate_top_decile_raw"],
        ascending=[False, True, False],
    ).head(18)
    rows: list[list[object]] = []
    for _, row in sub.iterrows():
        rows.append([
            fmt_cell(row["run_id"]),
            fmt_cell(row["horizon_sec"], "int"),
            short_market(row),
            fmt_cell(row["n_classifiable"], "int"),
            fmt_cell(row["ofi_hit_rate_top_decile"], "pct"),
            fmt_cell(row["ofi_hit_rate_top_decile_raw"], "pct"),
            fmt_cell(row["ofi_top_decile_n"], "int"),
            "yes" if bool(row.get("ofi_metric_reportable")) else "raw only",
            fmt_cell(row["edge_after_cost_bps"], "bps"),
        ])
    return markdown_table(
        ["run", "h", "market", "n class", "public hit", "raw hit", "top n", "status", "cost edge"],
        rows,
    )


def positive_edge_table(results: pd.DataFrame) -> str:
    sub = results[results["edge_after_cost_bps"].gt(0)].copy()
    if sub.empty:
        return "_No positive post-cost rows survived the reporting guard._"
    sub = sub.sort_values("edge_after_cost_bps", ascending=False)
    rows: list[list[object]] = []
    for _, row in sub.iterrows():
        rows.append([
            fmt_cell(row["run_id"]),
            fmt_cell(row["horizon_sec"], "int"),
            short_market(row),
            fmt_cell(row["family"]),
            fmt_cell(row["ofi_hit_rate_top_decile"], "pct"),
            fmt_cell(row["ofi_directional_return_top_decile_bps"], "bps"),
            fmt_cell(row["edge_after_cost_bps"], "bps"),
            fmt_cell(row["verdict"]),
        ])
    return markdown_table(
        ["run", "h", "market", "family", "hit", "dir ret", "cost edge", "verdict"],
        rows,
    )


def surface_table(surface: pd.DataFrame) -> str:
    if surface.empty:
        return "_No horizon-surface rows._"
    sub = surface.sort_values(["hit_rate", "directional_return_bps"], ascending=False).head(12)
    rows: list[list[object]] = []
    for _, row in sub.iterrows():
        rows.append([
            fmt_cell(row["horizon_sec"], "int"),
            fmt_cell(row["decile"], "int"),
            fmt_cell(row["ofi_level"]),
            fmt_cell(row["hit_rate"], "pct"),
            fmt_cell(row["directional_return_bps"], "bps"),
            fmt_cell(row["n"], "int"),
            fmt_cell(row["top_family"]),
            fmt_cell(row["top_family_share"], "pct"),
        ])
    return markdown_table(
        ["h", "decile", "level", "hit", "dir ret", "n", "top family", "share"],
        rows,
    )


def write_note(
    results: pd.DataFrame,
    deciles: pd.DataFrame,
    surface: pd.DataFrame,
    maker: pd.DataFrame,
    plot_paths: list[Path],
    maker_plot: Path | None,
    ws_latency_ms: int,
) -> None:
    NOTE.parent.mkdir(parents=True, exist_ok=True)
    d5_top = decile_row(deciles, 5, 10)
    d30_top = decile_row(deciles, 30, 10)
    d300_low = decile_row(deciles, 300, 1)
    d300_top = decile_row(deciles, 300, 10)
    headline_signal = decile_sentence(d5_top)

    family = family_rollup(results)
    family_lines = []
    for _, row in family.iterrows():
        cat = row["category"]
        if cat in {"Finance"}:
            continue
        hit_text = pct(float(row["median_5s_hit"])) if np.isfinite(row["median_5s_hit"]) else "n/a"
        edge_text = bps(float(row["mean_edge_after_cost_bps"])) if np.isfinite(row["mean_edge_after_cost_bps"]) else "n/a"
        family_lines.append(
            f"- {cat}: {int(row['n_trades']):,} trades across {int(row['n_markets'])} markets; "
            f"{int(row['primary_markets'])} primary-read markets and "
            f"{int(row['reportable_markets'])} reportable per-market 5s OFI rows; "
            f"median reportable 5s hit {hit_text}; mean post-cost overlay {edge_text}."
        )
    if not family_lines:
        family_lines.append("- No family rollup rows were large enough for commentary.")

    plot_refs = [f"![]({rel_plot(path)})" for path in plot_paths if "decile_hit_rate" in path.name]
    surface_refs = [
        f"![]({rel_plot(path)})"
        for path in plot_paths
        if "ofi_surface" in path.name
    ]
    scatter_refs = [
        f"![]({rel_plot(path)})"
        for path in plot_paths
        if "ofi_scatter" in path.name
    ]
    maker_ref = f"![]({rel_plot(maker_plot)})" if maker_plot else "No maker fill timeline was generated."
    maker_count = int(results[results["horizon_sec"].eq(5)]["maker_fill_count"].sum()) if not results.empty else 0
    maker_net = float(results[results["horizon_sec"].eq(5)]["maker_net_edge_bps_raw"].mean()) if not results.empty else math.nan
    reportable_rows = int(results["ofi_metric_reportable"].fillna(False).sum()) if "ofi_metric_reportable" in results else 0
    suppressed_rows = int((~results["ofi_metric_reportable"].fillna(False)).sum()) if "ofi_metric_reportable" in results else 0

    note = f"""---
tags: [dali, block-a1, results]
---

# Block A1 Results

## Headline

The material Block A1 win is sign convention: live `last_trade_price.side` is now established as token-side aggressor direction, which unblocks live OFI/TFI work. The cleanest depth-normalized OFI characterization is the pre-cost 5s top-decile aggregate, {headline_signal}. Crypto and sports carry the read; geopolitics is useful but thinner; AI/product is a single thin live sample; equity index and single-stock activity are caveats only. This remains signal characterization, not a tradeable/not-tradeable decision.

## Sign Convention Resolution

- A0 + A0b inspected 8,158 `last_trade_price` events.
- 847 were classifiable from subsequent book transitions.
- `P(reported.side == BUY | inferred BUY)` was 99.9%; `P(reported.side == BUY | inferred SELL)` was 1.7%.
- A1 therefore treats live `last_trade_price.side` as token-side aggressor.

## Capture Audit Summary

- A0 totals matched the final audit: 4,326 `book`, 1,253,183 `price_change`, 50,630 `best_bid_ask`, 2,095 `last_trade_price`, 8,427 `new_market`.
- A0b totals matched the final audit: 12,212 `book`, 842,267 `price_change`, 58,660 `best_bid_ask`, 6,063 `last_trade_price`, 3,570 `new_market`, 20 `tick_size_change`, 3 `market_resolved`.
- Gap logs: A0 had 4 `disconnect_or_error` entries; A0b had 1. Flanking windows were kept.
- `market_resolved` events were honored by dropping post-resolution rows per asset.

## Depth-Normalized Aggregate

{chr(10).join(plot_refs)}

The pooled aggregate uses `OFI_scaled = OFI / mean_depth_at_touch` and bins on absolute signal magnitude rather than market identity. OFI levels are percentile labels inside each horizon, not fixed physical units: deciles 1-3 are low, 4-7 are middle, 8-9 are high, and 10 is extreme. The 5s top decile is the headline because it is the cleanest high-magnitude bin; the 30s top decile is weaker but still elevated ({decile_sentence(d30_top)}). The 300s structure is not a clean monotone OFI story: the smallest-magnitude bin is unusually strong ({decile_sentence(d300_low)}) while the top-magnitude bin is only {decile_sentence(d300_top)}. Treat 300s as a QA caveat, not the headline.

## Horizon Surface

{chr(10).join(surface_refs)}

The surface diagnostic recomputes the depth-normalized aggregate at horizons 1, 2, 3, 5, 10, 15, 30, 60, 120, and 300 seconds. The 3D plot is included because it is good for seeing the ridge shape at a glance. The heatmaps are more useful for reading exact cells because horizons are log-spaced, deciles are discrete buckets, and the 300s low-OFI behavior can otherwise look like a smooth surface even when it is a single bucket effect. Best surface cells by hit rate:

{surface_table(surface)}

## Per-Family Read

{chr(10).join(family_lines)}

Per-market hit rates are diagnostic only; sparse or degenerate top-decile rows are suppressed in the public columns and kept only in raw audit columns. The CSV now has {reportable_rows} reportable OFI rows and {suppressed_rows} suppressed OFI rows under the minimum classifiable/top-decile guard. AI/product cannot validate the Block B finding here: the live sample has only one primary-threshold-ish market and wide uncertainty. A2 should explicitly target AI/product markets rather than relying on incidental flow. Equity-index and single-stock markets are too dead in A0/A0b to report family statistics.

## Per-Market Breakdown

The table below is the 5s horizon because that is the cleanest aggregate A1 result. Blank `n/a` public hit or cost cells usually mean the row was suppressed by the reporting guard, not that raw data was missing.

{per_market_table(results, 5)}

High individual-market hit-rate rows need extra care. Public rows survived the guard; `raw only` rows are retained for audit but should not be cited as standalone evidence.

{high_hit_table(results)}

Positive post-cost rows after the reporting guard are mostly longer-horizon crypto/geopolitics diagnostics, not deployment recommendations.

{positive_edge_table(results)}

## Per-Market Scatter Diagnostics

These sampled scatter plots were generated during A1 and are now linked here rather than left unused. They show raw 30s OFI versus 30s forward return for the most active markets; use them to spot outliers, regime mixtures, and thin linear fits before trusting any individual hit rate.

{chr(10).join(scatter_refs)}

## Maker Simulation Summary

{maker_ref}

The passive maker proxy found {maker_count:,} touch-fill observations in the 5s horizon panel. Mean queue-blind maker net edge after rebate and 5s adverse selection was {bps(maker_net)} in the raw proxy, but this is not a deployable edge estimate. The proxy follows the Domah audit pattern of using future prints as fill evidence, but differs because A1 uses live CLOB `last_trade_price` prints and current book touch, not historical wallet-address anchored copy fills. Queue position, cancel latency, and partial queue priority are not modeled.

## Cost Overlay Summary

Cost columns use the current Polymarket formula `fee = shares * fee_rate * p * (1 - p)` and normalize fee, half-spread, and latency slippage onto the same directional-return bps denominator. The previous A1 draft overstated latency slippage because pandas loaded capture timestamps at microsecond resolution while the latency offset was added as nanoseconds; this rerun converts timestamps to `datetime64[ns]` before applying the {ws_latency_ms} ms WS latency assumption. Midas has request timeout settings but no explicit WS execution latency config. The cost overlay is a diagnostic column, not a deployment verdict.

## A2 Design Recommendations

- After reviewing this cost-QA rerun, run a 1-2 week VPS capture with the A1 wrapper/analyzer unchanged.
- Add a targeted AI/product panel with active markets selected by live trade-rate, not just quote activity.
- Keep crypto 4h up/down windows in the panel because they provide dense live trade prints and clean horizon structure.
- Keep sports game-line markets, but separate live/in-game from pre-game when possible.
- Keep geopolitics as fee-free robustness, but do not overweight it in the cross-family headline.
- Remove equity-index and single-stock names unless pre-screened live flow is materially higher.

## Caveats

- This is one 24h A0 panel plus one 12h A0b replacement panel; thin markets remain labeled, not excluded.
- `best_bid_ask` never mutates executable state; OFI is from `book` plus `price_change`.
- Live WS `last_trade_price` messages do not expose the historical CTF Exchange `taker = address(this)` artifact; all A1 math uses raw unfiltered live data.
- The PSG Champions League leg is negative-risk and should not be pooled blindly with clean binary markets.
- Bootstrap intervals use time-contiguous chunks, but the sample is still short.

Recommended next action for Justin: review the regenerated cost overlay and, if the corrected 5s signal/cost picture is acceptable, approve A2 as a 1-2 week VPS capture with a targeted AI/product sleeve and continued crypto 4h up/down coverage.
"""
    NOTE.write_text(note, encoding="utf-8")


def update_todo() -> None:
    if not TODO.exists():
        return
    text = TODO.read_text(encoding="utf-8")
    replacement = """### Block A1: Live OFI/Maker sniff test ✅ (2026-05-28)
A0/A0b replayed into `data/analysis/block_a1_features.parquet`; cost-QA diagnostics written to `notes/block_a1_results.md`.

- [x] Live sign convention resolved on A0 + A0b
- [x] Capture audits confirmed clean
- [x] Batch replay wrapper added
- [x] Depth-normalized OFI diagnostics written
- [x] Maker proxy and corrected cost overlay written

### NEXT — Block A2: Longer live capture
- [ ] Review corrected A1 cost overlay before provisioning VPS
- [ ] Provision VPS for continuous 1-2 week Dali capture if A1 cost-QA is accepted
- [ ] Add targeted AI/product markets selected by live trade-rate
- [ ] Continue crypto 4h up/down and sports game-line panels
- [ ] Re-run A1 analyzer unchanged on the longer sample
"""
    pattern = re.compile(
        r"### NOW — Block A0: Live OFI Capture.*?(?=### Block C:)",
        flags=re.DOTALL,
    )
    if pattern.search(text):
        text = pattern.sub(replacement + "\n", text)
    elif "### Block A1: Live OFI/Maker sniff test" in text:
        existing = re.compile(
            r"### Block A1: Live OFI/Maker sniff test.*?(?=### Block C:)",
            flags=re.DOTALL,
        )
        text = existing.sub(replacement + "\n", text)
    else:
        marker = "## dali\n\n"
        text = text.replace(marker, marker + replacement + "\n", 1)
    TODO.write_text(text, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--features", type=Path, default=FEATURES)
    parser.add_argument("--results", type=Path, default=RESULTS)
    parser.add_argument("--deciles", type=Path, default=DECILES)
    parser.add_argument("--surface", type=Path, default=SURFACE)
    parser.add_argument("--ws-latency-ms", type=int, default=DEFAULT_WS_LATENCY_MS)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    PLOTS.mkdir(parents=True, exist_ok=True)
    df = load_features(args.features)
    analysis_horizons = tuple(sorted(set(HORIZONS) | set(SURFACE_HORIZONS)))
    df = add_signal_frames(df, analysis_horizons)
    results, maker = market_panel(df, args.ws_latency_ms)
    deciles = decile_aggregate(df, results)
    surface = horizon_surface_aggregate(df, results)

    args.results.parent.mkdir(parents=True, exist_ok=True)
    results.loc[:, RESULT_COLUMNS].to_csv(args.results, index=False)
    deciles.to_csv(args.deciles, index=False)
    surface.to_csv(args.surface, index=False)

    plot_paths = []
    plot_paths.extend(plot_deciles(deciles))
    plot_paths.extend(plot_surface_diagnostics(surface))
    plot_paths.extend(plot_scatters(df, results))
    maker_plot = plot_maker_timeline(maker)
    write_note(results, deciles, surface, maker, plot_paths, maker_plot, args.ws_latency_ms)
    update_todo()

    print(f"features: {display_path(args.features)} ({len(df):,} rows)")
    print(f"results: {display_path(args.results)} ({len(results):,} rows)")
    print(f"deciles: {display_path(args.deciles)} ({len(deciles):,} rows)")
    print(f"surface: {display_path(args.surface)} ({len(surface):,} rows)")
    print(f"plots: {display_path(PLOTS)}")
    print(f"note: {display_path(NOTE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
