"""Join-2d calibration tests — synthetic fills only; pure computation, no venue/network.

The synthetic scenario is built so the three queue models genuinely disagree (a cancel
lands at our level while size rests BEHIND us — the one case where attribution matters):

* ``book`` @ts1000: bid 0.47×100 / ask 0.49×100 → our BUY joins behind 100.
* ``price_change`` @ts1100: the 0.47 level grows to 150 → 50 contracts now rest BEHIND us.
* ``price_change`` @ts1200: the level drops to 90 → a 60-contract CANCEL to attribute:
  Optimistic advances 60 (ahead 40), RiskAverse only the logical floor 10 (ahead 90),
  ProbQueue(f) in between — monotone in ``f``.
* ``last_trade`` @ts1300: SELL 120 @0.47 → fill = the overflow past our queue_ahead, so the
  filled qty differs per model — the bracket the calibration collapses.

Ground truth: "observed" fills are generated by replaying with ``ProbQueue(f_true)``; the
fit must recover ``f_true`` exactly when it is on the grid.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from polymarket.execution.maker.mm_calibration import (
    DEFAULT_F_GRID,
    ObservedFills,
    bracket_collapse_report,
    fit_prob_queue_f,
    main,
    render_report,
)
from polymarket.execution.maker.mm_engine_bridge import ensure_mm_engine_importable

ensure_mm_engine_importable()
from mm_engine.engine import BACKTEST, run_engine  # noqa: E402
from mm_engine.fees import FeeModel  # noqa: E402
from mm_engine.interfaces import MarketEvent  # noqa: E402
from mm_engine.latency_models import ConstantLatency  # noqa: E402
from mm_engine.queue_models import OptimisticQueue, ProbQueue, RiskAverseQueue  # noqa: E402
from mm_engine.strategies import SymmetricQuoter  # noqa: E402

PARAMS = {"half_spread": 0.01, "size": 100.0, "tick": 0.001}


def _book(ts: int, bid: float, ask: float, bid_sz: float, ask_sz: float) -> MarketEvent:
    return MarketEvent("book", "t1", ts, "", 0, {
        "asset_id": "t1",
        "bids": [{"price": bid, "size": bid_sz}],
        "asks": [{"price": ask, "size": ask_sz}],
    })


def _pc(ts: int, side: str, price: float, new_size: float) -> MarketEvent:
    return MarketEvent("price_change", "t1", ts, "", 0, {
        "asset_id": "t1", "side": side, "price": price, "size": new_size,
    })


def _trade(ts: int, side: str, price: float, size: float) -> MarketEvent:
    return MarketEvent("last_trade", "t1", ts, "", 0, {
        "asset_id": "t1", "side": side, "price": price, "size": size,
    })


FEED = [
    _book(1000, 0.47, 0.49, 100.0, 100.0),
    _pc(1100, "BUY", 0.47, 150.0),   # 50 contracts join BEHIND us
    _pc(1200, "BUY", 0.47, 90.0),    # 60-contract cancel → attribution differs per model
    _trade(1300, "SELL", 0.47, 120.0),
]


def _observed_for(f_true: float) -> ObservedFills:
    res = run_engine(
        list(FEED),
        strategy=SymmetricQuoter(),
        queue_model=ProbQueue(f=f_true),
        latency_model=ConstantLatency(0.0),
        mode=BACKTEST,
        params=PARAMS,
        fee_model=FeeModel.fee_free_model(),
    )
    assert res.fill_count >= 1, "scenario must produce a fill for the fit to target"
    return ObservedFills.from_fill_records(res.fills)


# --------------------------------------------------------------------------------------
# the scenario really separates the models (precondition for everything else)
# --------------------------------------------------------------------------------------

def test_models_disagree_on_the_synthetic_scenario() -> None:
    def qty(model) -> float:
        return run_engine(
            list(FEED), strategy=SymmetricQuoter(), queue_model=model,
            latency_model=ConstantLatency(0.0), mode=BACKTEST, params=PARAMS,
            fee_model=FeeModel.fee_free_model(),
        ).filled_qty

    opt, ra, prob = qty(OptimisticQueue()), qty(RiskAverseQueue()), qty(ProbQueue(f=0.5))
    assert opt > prob > ra                     # a real bracket, not a degenerate point
    assert opt == pytest.approx(80.0)          # ahead 40 → overflow 80
    assert ra == pytest.approx(30.0)           # ahead 90 → overflow 30


# --------------------------------------------------------------------------------------
# f fit — recovers ground truth
# --------------------------------------------------------------------------------------

@pytest.mark.parametrize("f_true", [0.2, 0.75, 2.0])
def test_fit_recovers_f_true_on_grid(f_true: float) -> None:
    observed = _observed_for(f_true)
    fit = fit_prob_queue_f(FEED, observed, params=PARAMS, latency_ms=0.0)
    assert fit["f_star"] == pytest.approx(f_true)
    assert fit["best"]["qty_gap"] == pytest.approx(0.0)


def test_fit_grid_rows_are_monotone_in_f() -> None:
    """More f → more cancel volume attributed ahead of us → more fills (weakly)."""
    observed = _observed_for(0.5)
    fit = fit_prob_queue_f(FEED, observed, params=PARAMS, latency_ms=0.0)
    qtys = [row["modeled_filled_qty"] for row in fit["grid"]]
    assert qtys == sorted(qtys)
    assert len(qtys) == len(DEFAULT_F_GRID)


# --------------------------------------------------------------------------------------
# end-to-end pipeline: latency fit + calibrate hook + bracket-collapse report
# --------------------------------------------------------------------------------------

def test_bracket_collapse_report_end_to_end() -> None:
    observed = _observed_for(0.75)
    latency_samples = [180.0, 190.0, 200.0, 210.0, 220.0]
    report = bracket_collapse_report(
        FEED, observed, params=PARAMS, latency_samples_ms=latency_samples,
    )

    b = report["bracket"]
    # the bracket holds and the fitted point sits inside it, on the observed rate
    assert b["bracket_holds"] is True
    assert b["risk_averse"]["filled_qty"] <= b["fitted_prob"]["filled_qty"] <= b["optimistic"]["filled_qty"]
    assert b["f_star"] == pytest.approx(0.75)
    assert b["fitted_gap_to_observed_qty"] == pytest.approx(0.0)
    assert b["bracket_width_qty"] > 0.0

    # the latency leg landed: trimmed mean applied to the replays + SampledLatency refit
    assert report["latency"]["applied_constant_ms"] == pytest.approx(200.0)
    assert report["latency"]["sampled_latency_after_calibrate"]["mean"] == pytest.approx(200.0)

    # the frozen protocol hook was invoked end-to-end (and is, by design, a no-op stub)
    assert report["calibrate_hook"]["invoked"] is True
    assert report["calibrate_hook"]["returned"] is None

    text = render_report(report)
    assert "bracket-collapse" in text and "ProbQueue(f=0.75)" in text


def test_report_without_latency_samples_keeps_zero_ms_and_flags_it() -> None:
    observed = _observed_for(0.5)
    report = bracket_collapse_report(FEED, observed, params=PARAMS)
    assert report["latency"]["applied_constant_ms"] == 0.0
    assert "no latency samples" in report["latency"]["note"]


def test_observed_fills_from_fill_records_sums_qty() -> None:
    obs = ObservedFills.from_fill_records([
        {"qty": 30.0}, {"qty": 12.5}, {"qty": None}, {"no_qty": 1},
    ])
    assert obs.filled_qty == pytest.approx(42.5)
    assert obs.fill_count == 2


# --------------------------------------------------------------------------------------
# CLI (`--mode mm_calibrate`) — file-in/file-out
# --------------------------------------------------------------------------------------

def test_main_end_to_end_on_files(tmp_path: Path) -> None:
    events_path = tmp_path / "events.jsonl"
    with events_path.open("w", encoding="utf-8") as fh:
        for ev in FEED:
            fh.write(json.dumps({
                "type": ev.type, "token_id": ev.token_id, "ts_exchange": ev.ts_exchange,
                "payload": ev.payload,
            }) + "\n")
        fh.write(json.dumps({"gap": "test_gap_at_stream_end"}) + "\n")

    observed = _observed_for(0.75)
    fills_path = tmp_path / "fills.jsonl"
    fills_path.write_text(
        json.dumps({"qty": observed.filled_qty}) + "\n", encoding="utf-8"
    )
    out_path = tmp_path / "report.json"

    rc = main({
        "POLYMARKET_MM_CALIBRATE_EVENTS": str(events_path),
        "POLYMARKET_MM_CALIBRATE_FILLS": str(fills_path),
        "POLYMARKET_MM_CALIBRATE_OUT": str(out_path),
        "POLYMARKET_MM_BRIDGE_HALF_SPREAD": "0.01",
        "MAKER_SIZE_CONTRACTS": "100",
    })
    assert rc == 0
    report = json.loads(out_path.read_text(encoding="utf-8"))
    assert report["bracket"]["f_star"] == pytest.approx(0.75)
    assert report["bracket"]["bracket_holds"] is True


def test_main_returns_2_on_missing_inputs() -> None:
    assert main({}) == 2
    assert main({"POLYMARKET_MM_CALIBRATE_EVENTS": "/nonexistent/events.jsonl",
                 "POLYMARKET_MM_CALIBRATE_FILLS": "/nonexistent/fills.jsonl"}) == 2
